name: CI

on:
  push:
    branches: [ci]

jobs:
  build:
    runs-on: macos-10.15
    timeout-minutes: 30
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
    - name: Find Scheme of Default Project
      run: echo "::set-env name=SCHEME::$(xcodebuild -list -json | jq -r '.project.schemes[0]')"
    - name: Build
      run: xcodebuild -scheme "$SCHEME" CODE_SIGN_IDENTITY=-
